spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/gestionstock?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: administrateur_gs
        password: +Mb9UT!T]zbWU'+
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate.session_factory.statement_inspector: com.thomas.gestionDeStock.inspector.MyStatementInspector
server:
    port: 8081

flickr:
    apiKey: df7c9bb5a59e8408f9a0810dafec577e
    apiSecret: 2a3935bd96d7acf9
    appKey : 72157720926912965-84b1d48e37e69e3a
    appSecret: c5e6ec0851d1f2c1

springdoc:
    api-docs:
        path: /v3/api-docs         # Chemin pour accéder à la documentation OpenAPI JSON
    swagger-ui:
        path: /swagger-ui.html      # Chemin pour accéder à l'interface utilisateur Swagger
        operationsSorter: method    # Tri des opérations par méthode
        tagsSorter: alpha           # Tri des tags par ordre alphabétique
        disable-swagger-default-url: true  # Désactive l'URL par défaut de Swagger
