spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/gestionstock?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: administrateur_gs
        password: +Mb9UT!T]zbWU'+
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        show-sql: false
        hibernate:
            ddl-auto: update

server:
    port: 8081